# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/samuel/repos/cdd-openapi-test-harness/cdd-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/samuel/repos/cdd-openapi-test-harness/cdd-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"simdjson_Development\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/samuel/repos/cdd-openapi-test-harness/cdd-cpp/CMakeFiles /Users/samuel/repos/cdd-openapi-test-harness/cdd-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/samuel/repos/cdd-openapi-test-harness/cdd-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cdd_lib

# Build rule for target.
cdd_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cdd_lib
.PHONY : cdd_lib

# fast build rule for target.
cdd_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/build
.PHONY : cdd_lib/fast

#=============================================================================
# Target rules for targets named cdd-cpp

# Build rule for target.
cdd-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cdd-cpp
.PHONY : cdd-cpp

# fast build rule for target.
cdd-cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-cpp.dir/build.make CMakeFiles/cdd-cpp.dir/build
.PHONY : cdd-cpp/fast

#=============================================================================
# Target rules for targets named cdd-tests

# Build rule for target.
cdd-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cdd-tests
.PHONY : cdd-tests

# fast build rule for target.
cdd-tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/build
.PHONY : cdd-tests/fast

#=============================================================================
# Target rules for targets named test_simdjson_2

# Build rule for target.
test_simdjson_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_simdjson_2
.PHONY : test_simdjson_2

# fast build rule for target.
test_simdjson_2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simdjson_2.dir/build.make CMakeFiles/test_simdjson_2.dir/build
.PHONY : test_simdjson_2/fast

#=============================================================================
# Target rules for targets named simdjson

# Build rule for target.
simdjson: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simdjson
.PHONY : simdjson

# fast build rule for target.
simdjson/fast:
	$(MAKE) $(MAKESILENT) -f _deps/simdjson-build/CMakeFiles/simdjson.dir/build.make _deps/simdjson-build/CMakeFiles/simdjson.dir/build
.PHONY : simdjson/fast

src/cli/exceptions_stub.o: src/cli/exceptions_stub.cpp.o
.PHONY : src/cli/exceptions_stub.o

# target to build an object file
src/cli/exceptions_stub.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-cpp.dir/build.make CMakeFiles/cdd-cpp.dir/src/cli/exceptions_stub.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/cli/exceptions_stub.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simdjson_2.dir/build.make CMakeFiles/test_simdjson_2.dir/src/cli/exceptions_stub.cpp.o
.PHONY : src/cli/exceptions_stub.cpp.o

src/cli/exceptions_stub.i: src/cli/exceptions_stub.cpp.i
.PHONY : src/cli/exceptions_stub.i

# target to preprocess a source file
src/cli/exceptions_stub.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-cpp.dir/build.make CMakeFiles/cdd-cpp.dir/src/cli/exceptions_stub.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/cli/exceptions_stub.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simdjson_2.dir/build.make CMakeFiles/test_simdjson_2.dir/src/cli/exceptions_stub.cpp.i
.PHONY : src/cli/exceptions_stub.cpp.i

src/cli/exceptions_stub.s: src/cli/exceptions_stub.cpp.s
.PHONY : src/cli/exceptions_stub.s

# target to generate assembly for a file
src/cli/exceptions_stub.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-cpp.dir/build.make CMakeFiles/cdd-cpp.dir/src/cli/exceptions_stub.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/cli/exceptions_stub.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simdjson_2.dir/build.make CMakeFiles/test_simdjson_2.dir/src/cli/exceptions_stub.cpp.s
.PHONY : src/cli/exceptions_stub.cpp.s

src/cli/main.o: src/cli/main.cpp.o
.PHONY : src/cli/main.o

# target to build an object file
src/cli/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-cpp.dir/build.make CMakeFiles/cdd-cpp.dir/src/cli/main.cpp.o
.PHONY : src/cli/main.cpp.o

src/cli/main.i: src/cli/main.cpp.i
.PHONY : src/cli/main.i

# target to preprocess a source file
src/cli/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-cpp.dir/build.make CMakeFiles/cdd-cpp.dir/src/cli/main.cpp.i
.PHONY : src/cli/main.cpp.i

src/cli/main.s: src/cli/main.cpp.s
.PHONY : src/cli/main.s

# target to generate assembly for a file
src/cli/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-cpp.dir/build.make CMakeFiles/cdd-cpp.dir/src/cli/main.cpp.s
.PHONY : src/cli/main.cpp.s

src/cli/sync.o: src/cli/sync.cpp.o
.PHONY : src/cli/sync.o

# target to build an object file
src/cli/sync.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-cpp.dir/build.make CMakeFiles/cdd-cpp.dir/src/cli/sync.cpp.o
.PHONY : src/cli/sync.cpp.o

src/cli/sync.i: src/cli/sync.cpp.i
.PHONY : src/cli/sync.i

# target to preprocess a source file
src/cli/sync.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-cpp.dir/build.make CMakeFiles/cdd-cpp.dir/src/cli/sync.cpp.i
.PHONY : src/cli/sync.cpp.i

src/cli/sync.s: src/cli/sync.cpp.s
.PHONY : src/cli/sync.s

# target to generate assembly for a file
src/cli/sync.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-cpp.dir/build.make CMakeFiles/cdd-cpp.dir/src/cli/sync.cpp.s
.PHONY : src/cli/sync.cpp.s

src/client_sdk/emit.o: src/client_sdk/emit.cpp.o
.PHONY : src/client_sdk/emit.o

# target to build an object file
src/client_sdk/emit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/client_sdk/emit.cpp.o
.PHONY : src/client_sdk/emit.cpp.o

src/client_sdk/emit.i: src/client_sdk/emit.cpp.i
.PHONY : src/client_sdk/emit.i

# target to preprocess a source file
src/client_sdk/emit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/client_sdk/emit.cpp.i
.PHONY : src/client_sdk/emit.cpp.i

src/client_sdk/emit.s: src/client_sdk/emit.cpp.s
.PHONY : src/client_sdk/emit.s

# target to generate assembly for a file
src/client_sdk/emit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/client_sdk/emit.cpp.s
.PHONY : src/client_sdk/emit.cpp.s

src/client_sdk/parse.o: src/client_sdk/parse.cpp.o
.PHONY : src/client_sdk/parse.o

# target to build an object file
src/client_sdk/parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/client_sdk/parse.cpp.o
.PHONY : src/client_sdk/parse.cpp.o

src/client_sdk/parse.i: src/client_sdk/parse.cpp.i
.PHONY : src/client_sdk/parse.i

# target to preprocess a source file
src/client_sdk/parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/client_sdk/parse.cpp.i
.PHONY : src/client_sdk/parse.cpp.i

src/client_sdk/parse.s: src/client_sdk/parse.cpp.s
.PHONY : src/client_sdk/parse.s

# target to generate assembly for a file
src/client_sdk/parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/client_sdk/parse.cpp.s
.PHONY : src/client_sdk/parse.cpp.s

src/client_sdk_cli/emit.o: src/client_sdk_cli/emit.cpp.o
.PHONY : src/client_sdk_cli/emit.o

# target to build an object file
src/client_sdk_cli/emit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/client_sdk_cli/emit.cpp.o
.PHONY : src/client_sdk_cli/emit.cpp.o

src/client_sdk_cli/emit.i: src/client_sdk_cli/emit.cpp.i
.PHONY : src/client_sdk_cli/emit.i

# target to preprocess a source file
src/client_sdk_cli/emit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/client_sdk_cli/emit.cpp.i
.PHONY : src/client_sdk_cli/emit.cpp.i

src/client_sdk_cli/emit.s: src/client_sdk_cli/emit.cpp.s
.PHONY : src/client_sdk_cli/emit.s

# target to generate assembly for a file
src/client_sdk_cli/emit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/client_sdk_cli/emit.cpp.s
.PHONY : src/client_sdk_cli/emit.cpp.s

src/client_sdk_cli/parse.o: src/client_sdk_cli/parse.cpp.o
.PHONY : src/client_sdk_cli/parse.o

# target to build an object file
src/client_sdk_cli/parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/client_sdk_cli/parse.cpp.o
.PHONY : src/client_sdk_cli/parse.cpp.o

src/client_sdk_cli/parse.i: src/client_sdk_cli/parse.cpp.i
.PHONY : src/client_sdk_cli/parse.i

# target to preprocess a source file
src/client_sdk_cli/parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/client_sdk_cli/parse.cpp.i
.PHONY : src/client_sdk_cli/parse.cpp.i

src/client_sdk_cli/parse.s: src/client_sdk_cli/parse.cpp.s
.PHONY : src/client_sdk_cli/parse.s

# target to generate assembly for a file
src/client_sdk_cli/parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/client_sdk_cli/parse.cpp.s
.PHONY : src/client_sdk_cli/parse.cpp.s

src/docstrings/emit.o: src/docstrings/emit.cpp.o
.PHONY : src/docstrings/emit.o

# target to build an object file
src/docstrings/emit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/docstrings/emit.cpp.o
.PHONY : src/docstrings/emit.cpp.o

src/docstrings/emit.i: src/docstrings/emit.cpp.i
.PHONY : src/docstrings/emit.i

# target to preprocess a source file
src/docstrings/emit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/docstrings/emit.cpp.i
.PHONY : src/docstrings/emit.cpp.i

src/docstrings/emit.s: src/docstrings/emit.cpp.s
.PHONY : src/docstrings/emit.s

# target to generate assembly for a file
src/docstrings/emit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/docstrings/emit.cpp.s
.PHONY : src/docstrings/emit.cpp.s

src/docstrings/parse.o: src/docstrings/parse.cpp.o
.PHONY : src/docstrings/parse.o

# target to build an object file
src/docstrings/parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/docstrings/parse.cpp.o
.PHONY : src/docstrings/parse.cpp.o

src/docstrings/parse.i: src/docstrings/parse.cpp.i
.PHONY : src/docstrings/parse.i

# target to preprocess a source file
src/docstrings/parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/docstrings/parse.cpp.i
.PHONY : src/docstrings/parse.cpp.i

src/docstrings/parse.s: src/docstrings/parse.cpp.s
.PHONY : src/docstrings/parse.s

# target to generate assembly for a file
src/docstrings/parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/docstrings/parse.cpp.s
.PHONY : src/docstrings/parse.cpp.s

src/functions/emit.o: src/functions/emit.cpp.o
.PHONY : src/functions/emit.o

# target to build an object file
src/functions/emit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/functions/emit.cpp.o
.PHONY : src/functions/emit.cpp.o

src/functions/emit.i: src/functions/emit.cpp.i
.PHONY : src/functions/emit.i

# target to preprocess a source file
src/functions/emit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/functions/emit.cpp.i
.PHONY : src/functions/emit.cpp.i

src/functions/emit.s: src/functions/emit.cpp.s
.PHONY : src/functions/emit.s

# target to generate assembly for a file
src/functions/emit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/functions/emit.cpp.s
.PHONY : src/functions/emit.cpp.s

src/functions/parse.o: src/functions/parse.cpp.o
.PHONY : src/functions/parse.o

# target to build an object file
src/functions/parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/functions/parse.cpp.o
.PHONY : src/functions/parse.cpp.o

src/functions/parse.i: src/functions/parse.cpp.i
.PHONY : src/functions/parse.i

# target to preprocess a source file
src/functions/parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/functions/parse.cpp.i
.PHONY : src/functions/parse.cpp.i

src/functions/parse.s: src/functions/parse.cpp.s
.PHONY : src/functions/parse.s

# target to generate assembly for a file
src/functions/parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/functions/parse.cpp.s
.PHONY : src/functions/parse.cpp.s

src/google_discovery/parse.o: src/google_discovery/parse.cpp.o
.PHONY : src/google_discovery/parse.o

# target to build an object file
src/google_discovery/parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/google_discovery/parse.cpp.o
.PHONY : src/google_discovery/parse.cpp.o

src/google_discovery/parse.i: src/google_discovery/parse.cpp.i
.PHONY : src/google_discovery/parse.i

# target to preprocess a source file
src/google_discovery/parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/google_discovery/parse.cpp.i
.PHONY : src/google_discovery/parse.cpp.i

src/google_discovery/parse.s: src/google_discovery/parse.cpp.s
.PHONY : src/google_discovery/parse.s

# target to generate assembly for a file
src/google_discovery/parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/google_discovery/parse.cpp.s
.PHONY : src/google_discovery/parse.cpp.s

src/mcp/emit.o: src/mcp/emit.cpp.o
.PHONY : src/mcp/emit.o

# target to build an object file
src/mcp/emit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/mcp/emit.cpp.o
.PHONY : src/mcp/emit.cpp.o

src/mcp/emit.i: src/mcp/emit.cpp.i
.PHONY : src/mcp/emit.i

# target to preprocess a source file
src/mcp/emit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/mcp/emit.cpp.i
.PHONY : src/mcp/emit.cpp.i

src/mcp/emit.s: src/mcp/emit.cpp.s
.PHONY : src/mcp/emit.s

# target to generate assembly for a file
src/mcp/emit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/mcp/emit.cpp.s
.PHONY : src/mcp/emit.cpp.s

src/mcp/parse.o: src/mcp/parse.cpp.o
.PHONY : src/mcp/parse.o

# target to build an object file
src/mcp/parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/mcp/parse.cpp.o
.PHONY : src/mcp/parse.cpp.o

src/mcp/parse.i: src/mcp/parse.cpp.i
.PHONY : src/mcp/parse.i

# target to preprocess a source file
src/mcp/parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/mcp/parse.cpp.i
.PHONY : src/mcp/parse.cpp.i

src/mcp/parse.s: src/mcp/parse.cpp.s
.PHONY : src/mcp/parse.s

# target to generate assembly for a file
src/mcp/parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/mcp/parse.cpp.s
.PHONY : src/mcp/parse.cpp.s

src/mocks/emit.o: src/mocks/emit.cpp.o
.PHONY : src/mocks/emit.o

# target to build an object file
src/mocks/emit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/mocks/emit.cpp.o
.PHONY : src/mocks/emit.cpp.o

src/mocks/emit.i: src/mocks/emit.cpp.i
.PHONY : src/mocks/emit.i

# target to preprocess a source file
src/mocks/emit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/mocks/emit.cpp.i
.PHONY : src/mocks/emit.cpp.i

src/mocks/emit.s: src/mocks/emit.cpp.s
.PHONY : src/mocks/emit.s

# target to generate assembly for a file
src/mocks/emit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/mocks/emit.cpp.s
.PHONY : src/mocks/emit.cpp.s

src/mocks/parse.o: src/mocks/parse.cpp.o
.PHONY : src/mocks/parse.o

# target to build an object file
src/mocks/parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/mocks/parse.cpp.o
.PHONY : src/mocks/parse.cpp.o

src/mocks/parse.i: src/mocks/parse.cpp.i
.PHONY : src/mocks/parse.i

# target to preprocess a source file
src/mocks/parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/mocks/parse.cpp.i
.PHONY : src/mocks/parse.cpp.i

src/mocks/parse.s: src/mocks/parse.cpp.s
.PHONY : src/mocks/parse.s

# target to generate assembly for a file
src/mocks/parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/mocks/parse.cpp.s
.PHONY : src/mocks/parse.cpp.s

src/models/emit.o: src/models/emit.cpp.o
.PHONY : src/models/emit.o

# target to build an object file
src/models/emit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/models/emit.cpp.o
.PHONY : src/models/emit.cpp.o

src/models/emit.i: src/models/emit.cpp.i
.PHONY : src/models/emit.i

# target to preprocess a source file
src/models/emit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/models/emit.cpp.i
.PHONY : src/models/emit.cpp.i

src/models/emit.s: src/models/emit.cpp.s
.PHONY : src/models/emit.s

# target to generate assembly for a file
src/models/emit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/models/emit.cpp.s
.PHONY : src/models/emit.cpp.s

src/models/parse.o: src/models/parse.cpp.o
.PHONY : src/models/parse.o

# target to build an object file
src/models/parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/models/parse.cpp.o
.PHONY : src/models/parse.cpp.o

src/models/parse.i: src/models/parse.cpp.i
.PHONY : src/models/parse.i

# target to preprocess a source file
src/models/parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/models/parse.cpp.i
.PHONY : src/models/parse.cpp.i

src/models/parse.s: src/models/parse.cpp.s
.PHONY : src/models/parse.s

# target to generate assembly for a file
src/models/parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/models/parse.cpp.s
.PHONY : src/models/parse.cpp.s

src/openapi/emit.o: src/openapi/emit.cpp.o
.PHONY : src/openapi/emit.o

# target to build an object file
src/openapi/emit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/openapi/emit.cpp.o
.PHONY : src/openapi/emit.cpp.o

src/openapi/emit.i: src/openapi/emit.cpp.i
.PHONY : src/openapi/emit.i

# target to preprocess a source file
src/openapi/emit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/openapi/emit.cpp.i
.PHONY : src/openapi/emit.cpp.i

src/openapi/emit.s: src/openapi/emit.cpp.s
.PHONY : src/openapi/emit.s

# target to generate assembly for a file
src/openapi/emit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/openapi/emit.cpp.s
.PHONY : src/openapi/emit.cpp.s

src/openapi/parse.o: src/openapi/parse.cpp.o
.PHONY : src/openapi/parse.o

# target to build an object file
src/openapi/parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/openapi/parse.cpp.o
.PHONY : src/openapi/parse.cpp.o

src/openapi/parse.i: src/openapi/parse.cpp.i
.PHONY : src/openapi/parse.i

# target to preprocess a source file
src/openapi/parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/openapi/parse.cpp.i
.PHONY : src/openapi/parse.cpp.i

src/openapi/parse.s: src/openapi/parse.cpp.s
.PHONY : src/openapi/parse.s

# target to generate assembly for a file
src/openapi/parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/openapi/parse.cpp.s
.PHONY : src/openapi/parse.cpp.s

src/openapi/upgraders/upgrader.o: src/openapi/upgraders/upgrader.cpp.o
.PHONY : src/openapi/upgraders/upgrader.o

# target to build an object file
src/openapi/upgraders/upgrader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/openapi/upgraders/upgrader.cpp.o
.PHONY : src/openapi/upgraders/upgrader.cpp.o

src/openapi/upgraders/upgrader.i: src/openapi/upgraders/upgrader.cpp.i
.PHONY : src/openapi/upgraders/upgrader.i

# target to preprocess a source file
src/openapi/upgraders/upgrader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/openapi/upgraders/upgrader.cpp.i
.PHONY : src/openapi/upgraders/upgrader.cpp.i

src/openapi/upgraders/upgrader.s: src/openapi/upgraders/upgrader.cpp.s
.PHONY : src/openapi/upgraders/upgrader.s

# target to generate assembly for a file
src/openapi/upgraders/upgrader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/openapi/upgraders/upgrader.cpp.s
.PHONY : src/openapi/upgraders/upgrader.cpp.s

src/orm/emit.o: src/orm/emit.cpp.o
.PHONY : src/orm/emit.o

# target to build an object file
src/orm/emit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/orm/emit.cpp.o
.PHONY : src/orm/emit.cpp.o

src/orm/emit.i: src/orm/emit.cpp.i
.PHONY : src/orm/emit.i

# target to preprocess a source file
src/orm/emit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/orm/emit.cpp.i
.PHONY : src/orm/emit.cpp.i

src/orm/emit.s: src/orm/emit.cpp.s
.PHONY : src/orm/emit.s

# target to generate assembly for a file
src/orm/emit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/orm/emit.cpp.s
.PHONY : src/orm/emit.cpp.s

src/server/emit.o: src/server/emit.cpp.o
.PHONY : src/server/emit.o

# target to build an object file
src/server/emit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/server/emit.cpp.o
.PHONY : src/server/emit.cpp.o

src/server/emit.i: src/server/emit.cpp.i
.PHONY : src/server/emit.i

# target to preprocess a source file
src/server/emit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/server/emit.cpp.i
.PHONY : src/server/emit.cpp.i

src/server/emit.s: src/server/emit.cpp.s
.PHONY : src/server/emit.s

# target to generate assembly for a file
src/server/emit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/server/emit.cpp.s
.PHONY : src/server/emit.cpp.s

src/server/parse.o: src/server/parse.cpp.o
.PHONY : src/server/parse.o

# target to build an object file
src/server/parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/server/parse.cpp.o
.PHONY : src/server/parse.cpp.o

src/server/parse.i: src/server/parse.cpp.i
.PHONY : src/server/parse.i

# target to preprocess a source file
src/server/parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/server/parse.cpp.i
.PHONY : src/server/parse.cpp.i

src/server/parse.s: src/server/parse.cpp.s
.PHONY : src/server/parse.s

# target to generate assembly for a file
src/server/parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/server/parse.cpp.s
.PHONY : src/server/parse.cpp.s

src/tests/ast_test.o: src/tests/ast_test.cpp.o
.PHONY : src/tests/ast_test.o

# target to build an object file
src/tests/ast_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/ast_test.cpp.o
.PHONY : src/tests/ast_test.cpp.o

src/tests/ast_test.i: src/tests/ast_test.cpp.i
.PHONY : src/tests/ast_test.i

# target to preprocess a source file
src/tests/ast_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/ast_test.cpp.i
.PHONY : src/tests/ast_test.cpp.i

src/tests/ast_test.s: src/tests/ast_test.cpp.s
.PHONY : src/tests/ast_test.s

# target to generate assembly for a file
src/tests/ast_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/ast_test.cpp.s
.PHONY : src/tests/ast_test.cpp.s

src/tests/cli.o: src/tests/cli.cpp.o
.PHONY : src/tests/cli.o

# target to build an object file
src/tests/cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/cli.cpp.o
.PHONY : src/tests/cli.cpp.o

src/tests/cli.i: src/tests/cli.cpp.i
.PHONY : src/tests/cli.i

# target to preprocess a source file
src/tests/cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/cli.cpp.i
.PHONY : src/tests/cli.cpp.i

src/tests/cli.s: src/tests/cli.cpp.s
.PHONY : src/tests/cli.s

# target to generate assembly for a file
src/tests/cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/cli.cpp.s
.PHONY : src/tests/cli.cpp.s

src/tests/client_sdk_cli_test.o: src/tests/client_sdk_cli_test.cpp.o
.PHONY : src/tests/client_sdk_cli_test.o

# target to build an object file
src/tests/client_sdk_cli_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/client_sdk_cli_test.cpp.o
.PHONY : src/tests/client_sdk_cli_test.cpp.o

src/tests/client_sdk_cli_test.i: src/tests/client_sdk_cli_test.cpp.i
.PHONY : src/tests/client_sdk_cli_test.i

# target to preprocess a source file
src/tests/client_sdk_cli_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/client_sdk_cli_test.cpp.i
.PHONY : src/tests/client_sdk_cli_test.cpp.i

src/tests/client_sdk_cli_test.s: src/tests/client_sdk_cli_test.cpp.s
.PHONY : src/tests/client_sdk_cli_test.s

# target to generate assembly for a file
src/tests/client_sdk_cli_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/client_sdk_cli_test.cpp.s
.PHONY : src/tests/client_sdk_cli_test.cpp.s

src/tests/client_sdk_test.o: src/tests/client_sdk_test.cpp.o
.PHONY : src/tests/client_sdk_test.o

# target to build an object file
src/tests/client_sdk_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/client_sdk_test.cpp.o
.PHONY : src/tests/client_sdk_test.cpp.o

src/tests/client_sdk_test.i: src/tests/client_sdk_test.cpp.i
.PHONY : src/tests/client_sdk_test.i

# target to preprocess a source file
src/tests/client_sdk_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/client_sdk_test.cpp.i
.PHONY : src/tests/client_sdk_test.cpp.i

src/tests/client_sdk_test.s: src/tests/client_sdk_test.cpp.s
.PHONY : src/tests/client_sdk_test.s

# target to generate assembly for a file
src/tests/client_sdk_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/client_sdk_test.cpp.s
.PHONY : src/tests/client_sdk_test.cpp.s

src/tests/docstrings.o: src/tests/docstrings.cpp.o
.PHONY : src/tests/docstrings.o

# target to build an object file
src/tests/docstrings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/docstrings.cpp.o
.PHONY : src/tests/docstrings.cpp.o

src/tests/docstrings.i: src/tests/docstrings.cpp.i
.PHONY : src/tests/docstrings.i

# target to preprocess a source file
src/tests/docstrings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/docstrings.cpp.i
.PHONY : src/tests/docstrings.cpp.i

src/tests/docstrings.s: src/tests/docstrings.cpp.s
.PHONY : src/tests/docstrings.s

# target to generate assembly for a file
src/tests/docstrings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/docstrings.cpp.s
.PHONY : src/tests/docstrings.cpp.s

src/tests/emit.o: src/tests/emit.cpp.o
.PHONY : src/tests/emit.o

# target to build an object file
src/tests/emit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/emit.cpp.o
.PHONY : src/tests/emit.cpp.o

src/tests/emit.i: src/tests/emit.cpp.i
.PHONY : src/tests/emit.i

# target to preprocess a source file
src/tests/emit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/emit.cpp.i
.PHONY : src/tests/emit.cpp.i

src/tests/emit.s: src/tests/emit.cpp.s
.PHONY : src/tests/emit.s

# target to generate assembly for a file
src/tests/emit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/emit.cpp.s
.PHONY : src/tests/emit.cpp.s

src/tests/functions.o: src/tests/functions.cpp.o
.PHONY : src/tests/functions.o

# target to build an object file
src/tests/functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/functions.cpp.o
.PHONY : src/tests/functions.cpp.o

src/tests/functions.i: src/tests/functions.cpp.i
.PHONY : src/tests/functions.i

# target to preprocess a source file
src/tests/functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/functions.cpp.i
.PHONY : src/tests/functions.cpp.i

src/tests/functions.s: src/tests/functions.cpp.s
.PHONY : src/tests/functions.s

# target to generate assembly for a file
src/tests/functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/functions.cpp.s
.PHONY : src/tests/functions.cpp.s

src/tests/google_discovery.o: src/tests/google_discovery.cpp.o
.PHONY : src/tests/google_discovery.o

# target to build an object file
src/tests/google_discovery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/google_discovery.cpp.o
.PHONY : src/tests/google_discovery.cpp.o

src/tests/google_discovery.i: src/tests/google_discovery.cpp.i
.PHONY : src/tests/google_discovery.i

# target to preprocess a source file
src/tests/google_discovery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/google_discovery.cpp.i
.PHONY : src/tests/google_discovery.cpp.i

src/tests/google_discovery.s: src/tests/google_discovery.cpp.s
.PHONY : src/tests/google_discovery.s

# target to generate assembly for a file
src/tests/google_discovery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/google_discovery.cpp.s
.PHONY : src/tests/google_discovery.cpp.s

src/tests/http.o: src/tests/http.cpp.o
.PHONY : src/tests/http.o

# target to build an object file
src/tests/http.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/http.cpp.o
.PHONY : src/tests/http.cpp.o

src/tests/http.i: src/tests/http.cpp.i
.PHONY : src/tests/http.i

# target to preprocess a source file
src/tests/http.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/http.cpp.i
.PHONY : src/tests/http.cpp.i

src/tests/http.s: src/tests/http.cpp.s
.PHONY : src/tests/http.s

# target to generate assembly for a file
src/tests/http.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/http.cpp.s
.PHONY : src/tests/http.cpp.s

src/tests/main.o: src/tests/main.cpp.o
.PHONY : src/tests/main.o

# target to build an object file
src/tests/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/main.cpp.o
.PHONY : src/tests/main.cpp.o

src/tests/main.i: src/tests/main.cpp.i
.PHONY : src/tests/main.i

# target to preprocess a source file
src/tests/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/main.cpp.i
.PHONY : src/tests/main.cpp.i

src/tests/main.s: src/tests/main.cpp.s
.PHONY : src/tests/main.s

# target to generate assembly for a file
src/tests/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/main.cpp.s
.PHONY : src/tests/main.cpp.s

src/tests/mcp.o: src/tests/mcp.cpp.o
.PHONY : src/tests/mcp.o

# target to build an object file
src/tests/mcp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/mcp.cpp.o
.PHONY : src/tests/mcp.cpp.o

src/tests/mcp.i: src/tests/mcp.cpp.i
.PHONY : src/tests/mcp.i

# target to preprocess a source file
src/tests/mcp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/mcp.cpp.i
.PHONY : src/tests/mcp.cpp.i

src/tests/mcp.s: src/tests/mcp.cpp.s
.PHONY : src/tests/mcp.s

# target to generate assembly for a file
src/tests/mcp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/mcp.cpp.s
.PHONY : src/tests/mcp.cpp.s

src/tests/mcp_meta_tests.o: src/tests/mcp_meta_tests.cpp.o
.PHONY : src/tests/mcp_meta_tests.o

# target to build an object file
src/tests/mcp_meta_tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/mcp_meta_tests.cpp.o
.PHONY : src/tests/mcp_meta_tests.cpp.o

src/tests/mcp_meta_tests.i: src/tests/mcp_meta_tests.cpp.i
.PHONY : src/tests/mcp_meta_tests.i

# target to preprocess a source file
src/tests/mcp_meta_tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/mcp_meta_tests.cpp.i
.PHONY : src/tests/mcp_meta_tests.cpp.i

src/tests/mcp_meta_tests.s: src/tests/mcp_meta_tests.cpp.s
.PHONY : src/tests/mcp_meta_tests.s

# target to generate assembly for a file
src/tests/mcp_meta_tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/mcp_meta_tests.cpp.s
.PHONY : src/tests/mcp_meta_tests.cpp.s

src/tests/mcp_parse_fail_tests.o: src/tests/mcp_parse_fail_tests.cpp.o
.PHONY : src/tests/mcp_parse_fail_tests.o

# target to build an object file
src/tests/mcp_parse_fail_tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/mcp_parse_fail_tests.cpp.o
.PHONY : src/tests/mcp_parse_fail_tests.cpp.o

src/tests/mcp_parse_fail_tests.i: src/tests/mcp_parse_fail_tests.cpp.i
.PHONY : src/tests/mcp_parse_fail_tests.i

# target to preprocess a source file
src/tests/mcp_parse_fail_tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/mcp_parse_fail_tests.cpp.i
.PHONY : src/tests/mcp_parse_fail_tests.cpp.i

src/tests/mcp_parse_fail_tests.s: src/tests/mcp_parse_fail_tests.cpp.s
.PHONY : src/tests/mcp_parse_fail_tests.s

# target to generate assembly for a file
src/tests/mcp_parse_fail_tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/mcp_parse_fail_tests.cpp.s
.PHONY : src/tests/mcp_parse_fail_tests.cpp.s

src/tests/mocks.o: src/tests/mocks.cpp.o
.PHONY : src/tests/mocks.o

# target to build an object file
src/tests/mocks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/mocks.cpp.o
.PHONY : src/tests/mocks.cpp.o

src/tests/mocks.i: src/tests/mocks.cpp.i
.PHONY : src/tests/mocks.i

# target to preprocess a source file
src/tests/mocks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/mocks.cpp.i
.PHONY : src/tests/mocks.cpp.i

src/tests/mocks.s: src/tests/mocks.cpp.s
.PHONY : src/tests/mocks.s

# target to generate assembly for a file
src/tests/mocks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/mocks.cpp.s
.PHONY : src/tests/mocks.cpp.s

src/tests/models.o: src/tests/models.cpp.o
.PHONY : src/tests/models.o

# target to build an object file
src/tests/models.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/models.cpp.o
.PHONY : src/tests/models.cpp.o

src/tests/models.i: src/tests/models.cpp.i
.PHONY : src/tests/models.i

# target to preprocess a source file
src/tests/models.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/models.cpp.i
.PHONY : src/tests/models.cpp.i

src/tests/models.s: src/tests/models.cpp.s
.PHONY : src/tests/models.s

# target to generate assembly for a file
src/tests/models.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/models.cpp.s
.PHONY : src/tests/models.cpp.s

src/tests/openapi_parse.o: src/tests/openapi_parse.cpp.o
.PHONY : src/tests/openapi_parse.o

# target to build an object file
src/tests/openapi_parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/openapi_parse.cpp.o
.PHONY : src/tests/openapi_parse.cpp.o

src/tests/openapi_parse.i: src/tests/openapi_parse.cpp.i
.PHONY : src/tests/openapi_parse.i

# target to preprocess a source file
src/tests/openapi_parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/openapi_parse.cpp.i
.PHONY : src/tests/openapi_parse.cpp.i

src/tests/openapi_parse.s: src/tests/openapi_parse.cpp.s
.PHONY : src/tests/openapi_parse.s

# target to generate assembly for a file
src/tests/openapi_parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/openapi_parse.cpp.s
.PHONY : src/tests/openapi_parse.cpp.s

src/tests/orm.o: src/tests/orm.cpp.o
.PHONY : src/tests/orm.o

# target to build an object file
src/tests/orm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/orm.cpp.o
.PHONY : src/tests/orm.cpp.o

src/tests/orm.i: src/tests/orm.cpp.i
.PHONY : src/tests/orm.i

# target to preprocess a source file
src/tests/orm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/orm.cpp.i
.PHONY : src/tests/orm.cpp.i

src/tests/orm.s: src/tests/orm.cpp.s
.PHONY : src/tests/orm.s

# target to generate assembly for a file
src/tests/orm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/orm.cpp.s
.PHONY : src/tests/orm.cpp.s

src/tests/parse.o: src/tests/parse.cpp.o
.PHONY : src/tests/parse.o

# target to build an object file
src/tests/parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/parse.cpp.o
.PHONY : src/tests/parse.cpp.o

src/tests/parse.i: src/tests/parse.cpp.i
.PHONY : src/tests/parse.i

# target to preprocess a source file
src/tests/parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/parse.cpp.i
.PHONY : src/tests/parse.cpp.i

src/tests/parse.s: src/tests/parse.cpp.s
.PHONY : src/tests/parse.s

# target to generate assembly for a file
src/tests/parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/parse.cpp.s
.PHONY : src/tests/parse.cpp.s

src/tests/server.o: src/tests/server.cpp.o
.PHONY : src/tests/server.o

# target to build an object file
src/tests/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/server.cpp.o
.PHONY : src/tests/server.cpp.o

src/tests/server.i: src/tests/server.cpp.i
.PHONY : src/tests/server.i

# target to preprocess a source file
src/tests/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/server.cpp.i
.PHONY : src/tests/server.cpp.i

src/tests/server.s: src/tests/server.cpp.s
.PHONY : src/tests/server.s

# target to generate assembly for a file
src/tests/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/server.cpp.s
.PHONY : src/tests/server.cpp.s

src/tests/struct_test.o: src/tests/struct_test.cpp.o
.PHONY : src/tests/struct_test.o

# target to build an object file
src/tests/struct_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/struct_test.cpp.o
.PHONY : src/tests/struct_test.cpp.o

src/tests/struct_test.i: src/tests/struct_test.cpp.i
.PHONY : src/tests/struct_test.i

# target to preprocess a source file
src/tests/struct_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/struct_test.cpp.i
.PHONY : src/tests/struct_test.cpp.i

src/tests/struct_test.s: src/tests/struct_test.cpp.s
.PHONY : src/tests/struct_test.s

# target to generate assembly for a file
src/tests/struct_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/struct_test.cpp.s
.PHONY : src/tests/struct_test.cpp.s

src/tests/sync_test.o: src/tests/sync_test.cpp.o
.PHONY : src/tests/sync_test.o

# target to build an object file
src/tests/sync_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/sync_test.cpp.o
.PHONY : src/tests/sync_test.cpp.o

src/tests/sync_test.i: src/tests/sync_test.cpp.i
.PHONY : src/tests/sync_test.i

# target to preprocess a source file
src/tests/sync_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/sync_test.cpp.i
.PHONY : src/tests/sync_test.cpp.i

src/tests/sync_test.s: src/tests/sync_test.cpp.s
.PHONY : src/tests/sync_test.s

# target to generate assembly for a file
src/tests/sync_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/sync_test.cpp.s
.PHONY : src/tests/sync_test.cpp.s

src/tests/test_simdjson_2.o: src/tests/test_simdjson_2.cpp.o
.PHONY : src/tests/test_simdjson_2.o

# target to build an object file
src/tests/test_simdjson_2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simdjson_2.dir/build.make CMakeFiles/test_simdjson_2.dir/src/tests/test_simdjson_2.cpp.o
.PHONY : src/tests/test_simdjson_2.cpp.o

src/tests/test_simdjson_2.i: src/tests/test_simdjson_2.cpp.i
.PHONY : src/tests/test_simdjson_2.i

# target to preprocess a source file
src/tests/test_simdjson_2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simdjson_2.dir/build.make CMakeFiles/test_simdjson_2.dir/src/tests/test_simdjson_2.cpp.i
.PHONY : src/tests/test_simdjson_2.cpp.i

src/tests/test_simdjson_2.s: src/tests/test_simdjson_2.cpp.s
.PHONY : src/tests/test_simdjson_2.s

# target to generate assembly for a file
src/tests/test_simdjson_2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simdjson_2.dir/build.make CMakeFiles/test_simdjson_2.dir/src/tests/test_simdjson_2.cpp.s
.PHONY : src/tests/test_simdjson_2.cpp.s

src/tests/upgrader_test.o: src/tests/upgrader_test.cpp.o
.PHONY : src/tests/upgrader_test.o

# target to build an object file
src/tests/upgrader_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/upgrader_test.cpp.o
.PHONY : src/tests/upgrader_test.cpp.o

src/tests/upgrader_test.i: src/tests/upgrader_test.cpp.i
.PHONY : src/tests/upgrader_test.i

# target to preprocess a source file
src/tests/upgrader_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/upgrader_test.cpp.i
.PHONY : src/tests/upgrader_test.cpp.i

src/tests/upgrader_test.s: src/tests/upgrader_test.cpp.s
.PHONY : src/tests/upgrader_test.s

# target to generate assembly for a file
src/tests/upgrader_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd-tests.dir/build.make CMakeFiles/cdd-tests.dir/src/tests/upgrader_test.cpp.s
.PHONY : src/tests/upgrader_test.cpp.s

src/utils/cpp_ast.o: src/utils/cpp_ast.cpp.o
.PHONY : src/utils/cpp_ast.o

# target to build an object file
src/utils/cpp_ast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/utils/cpp_ast.cpp.o
.PHONY : src/utils/cpp_ast.cpp.o

src/utils/cpp_ast.i: src/utils/cpp_ast.cpp.i
.PHONY : src/utils/cpp_ast.i

# target to preprocess a source file
src/utils/cpp_ast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/utils/cpp_ast.cpp.i
.PHONY : src/utils/cpp_ast.cpp.i

src/utils/cpp_ast.s: src/utils/cpp_ast.cpp.s
.PHONY : src/utils/cpp_ast.s

# target to generate assembly for a file
src/utils/cpp_ast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/utils/cpp_ast.cpp.s
.PHONY : src/utils/cpp_ast.cpp.s

src/utils/cpp_parser.o: src/utils/cpp_parser.cpp.o
.PHONY : src/utils/cpp_parser.o

# target to build an object file
src/utils/cpp_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/utils/cpp_parser.cpp.o
.PHONY : src/utils/cpp_parser.cpp.o

src/utils/cpp_parser.i: src/utils/cpp_parser.cpp.i
.PHONY : src/utils/cpp_parser.i

# target to preprocess a source file
src/utils/cpp_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/utils/cpp_parser.cpp.i
.PHONY : src/utils/cpp_parser.cpp.i

src/utils/cpp_parser.s: src/utils/cpp_parser.cpp.s
.PHONY : src/utils/cpp_parser.s

# target to generate assembly for a file
src/utils/cpp_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/utils/cpp_parser.cpp.s
.PHONY : src/utils/cpp_parser.cpp.s

src/utils/http.o: src/utils/http.cpp.o
.PHONY : src/utils/http.o

# target to build an object file
src/utils/http.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/utils/http.cpp.o
.PHONY : src/utils/http.cpp.o

src/utils/http.i: src/utils/http.cpp.i
.PHONY : src/utils/http.i

# target to preprocess a source file
src/utils/http.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/utils/http.cpp.i
.PHONY : src/utils/http.cpp.i

src/utils/http.s: src/utils/http.cpp.s
.PHONY : src/utils/http.s

# target to generate assembly for a file
src/utils/http.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cdd_lib.dir/build.make CMakeFiles/cdd_lib.dir/src/utils/http.cpp.s
.PHONY : src/utils/http.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... cdd-cpp"
	@echo "... cdd-tests"
	@echo "... cdd_lib"
	@echo "... simdjson"
	@echo "... test_simdjson_2"
	@echo "... src/cli/exceptions_stub.o"
	@echo "... src/cli/exceptions_stub.i"
	@echo "... src/cli/exceptions_stub.s"
	@echo "... src/cli/main.o"
	@echo "... src/cli/main.i"
	@echo "... src/cli/main.s"
	@echo "... src/cli/sync.o"
	@echo "... src/cli/sync.i"
	@echo "... src/cli/sync.s"
	@echo "... src/client_sdk/emit.o"
	@echo "... src/client_sdk/emit.i"
	@echo "... src/client_sdk/emit.s"
	@echo "... src/client_sdk/parse.o"
	@echo "... src/client_sdk/parse.i"
	@echo "... src/client_sdk/parse.s"
	@echo "... src/client_sdk_cli/emit.o"
	@echo "... src/client_sdk_cli/emit.i"
	@echo "... src/client_sdk_cli/emit.s"
	@echo "... src/client_sdk_cli/parse.o"
	@echo "... src/client_sdk_cli/parse.i"
	@echo "... src/client_sdk_cli/parse.s"
	@echo "... src/docstrings/emit.o"
	@echo "... src/docstrings/emit.i"
	@echo "... src/docstrings/emit.s"
	@echo "... src/docstrings/parse.o"
	@echo "... src/docstrings/parse.i"
	@echo "... src/docstrings/parse.s"
	@echo "... src/functions/emit.o"
	@echo "... src/functions/emit.i"
	@echo "... src/functions/emit.s"
	@echo "... src/functions/parse.o"
	@echo "... src/functions/parse.i"
	@echo "... src/functions/parse.s"
	@echo "... src/google_discovery/parse.o"
	@echo "... src/google_discovery/parse.i"
	@echo "... src/google_discovery/parse.s"
	@echo "... src/mcp/emit.o"
	@echo "... src/mcp/emit.i"
	@echo "... src/mcp/emit.s"
	@echo "... src/mcp/parse.o"
	@echo "... src/mcp/parse.i"
	@echo "... src/mcp/parse.s"
	@echo "... src/mocks/emit.o"
	@echo "... src/mocks/emit.i"
	@echo "... src/mocks/emit.s"
	@echo "... src/mocks/parse.o"
	@echo "... src/mocks/parse.i"
	@echo "... src/mocks/parse.s"
	@echo "... src/models/emit.o"
	@echo "... src/models/emit.i"
	@echo "... src/models/emit.s"
	@echo "... src/models/parse.o"
	@echo "... src/models/parse.i"
	@echo "... src/models/parse.s"
	@echo "... src/openapi/emit.o"
	@echo "... src/openapi/emit.i"
	@echo "... src/openapi/emit.s"
	@echo "... src/openapi/parse.o"
	@echo "... src/openapi/parse.i"
	@echo "... src/openapi/parse.s"
	@echo "... src/openapi/upgraders/upgrader.o"
	@echo "... src/openapi/upgraders/upgrader.i"
	@echo "... src/openapi/upgraders/upgrader.s"
	@echo "... src/orm/emit.o"
	@echo "... src/orm/emit.i"
	@echo "... src/orm/emit.s"
	@echo "... src/server/emit.o"
	@echo "... src/server/emit.i"
	@echo "... src/server/emit.s"
	@echo "... src/server/parse.o"
	@echo "... src/server/parse.i"
	@echo "... src/server/parse.s"
	@echo "... src/tests/ast_test.o"
	@echo "... src/tests/ast_test.i"
	@echo "... src/tests/ast_test.s"
	@echo "... src/tests/cli.o"
	@echo "... src/tests/cli.i"
	@echo "... src/tests/cli.s"
	@echo "... src/tests/client_sdk_cli_test.o"
	@echo "... src/tests/client_sdk_cli_test.i"
	@echo "... src/tests/client_sdk_cli_test.s"
	@echo "... src/tests/client_sdk_test.o"
	@echo "... src/tests/client_sdk_test.i"
	@echo "... src/tests/client_sdk_test.s"
	@echo "... src/tests/docstrings.o"
	@echo "... src/tests/docstrings.i"
	@echo "... src/tests/docstrings.s"
	@echo "... src/tests/emit.o"
	@echo "... src/tests/emit.i"
	@echo "... src/tests/emit.s"
	@echo "... src/tests/functions.o"
	@echo "... src/tests/functions.i"
	@echo "... src/tests/functions.s"
	@echo "... src/tests/google_discovery.o"
	@echo "... src/tests/google_discovery.i"
	@echo "... src/tests/google_discovery.s"
	@echo "... src/tests/http.o"
	@echo "... src/tests/http.i"
	@echo "... src/tests/http.s"
	@echo "... src/tests/main.o"
	@echo "... src/tests/main.i"
	@echo "... src/tests/main.s"
	@echo "... src/tests/mcp.o"
	@echo "... src/tests/mcp.i"
	@echo "... src/tests/mcp.s"
	@echo "... src/tests/mcp_meta_tests.o"
	@echo "... src/tests/mcp_meta_tests.i"
	@echo "... src/tests/mcp_meta_tests.s"
	@echo "... src/tests/mcp_parse_fail_tests.o"
	@echo "... src/tests/mcp_parse_fail_tests.i"
	@echo "... src/tests/mcp_parse_fail_tests.s"
	@echo "... src/tests/mocks.o"
	@echo "... src/tests/mocks.i"
	@echo "... src/tests/mocks.s"
	@echo "... src/tests/models.o"
	@echo "... src/tests/models.i"
	@echo "... src/tests/models.s"
	@echo "... src/tests/openapi_parse.o"
	@echo "... src/tests/openapi_parse.i"
	@echo "... src/tests/openapi_parse.s"
	@echo "... src/tests/orm.o"
	@echo "... src/tests/orm.i"
	@echo "... src/tests/orm.s"
	@echo "... src/tests/parse.o"
	@echo "... src/tests/parse.i"
	@echo "... src/tests/parse.s"
	@echo "... src/tests/server.o"
	@echo "... src/tests/server.i"
	@echo "... src/tests/server.s"
	@echo "... src/tests/struct_test.o"
	@echo "... src/tests/struct_test.i"
	@echo "... src/tests/struct_test.s"
	@echo "... src/tests/sync_test.o"
	@echo "... src/tests/sync_test.i"
	@echo "... src/tests/sync_test.s"
	@echo "... src/tests/test_simdjson_2.o"
	@echo "... src/tests/test_simdjson_2.i"
	@echo "... src/tests/test_simdjson_2.s"
	@echo "... src/tests/upgrader_test.o"
	@echo "... src/tests/upgrader_test.i"
	@echo "... src/tests/upgrader_test.s"
	@echo "... src/utils/cpp_ast.o"
	@echo "... src/utils/cpp_ast.i"
	@echo "... src/utils/cpp_ast.s"
	@echo "... src/utils/cpp_parser.o"
	@echo "... src/utils/cpp_parser.i"
	@echo "... src/utils/cpp_parser.s"
	@echo "... src/utils/http.o"
	@echo "... src/utils/http.i"
	@echo "... src/utils/http.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

